name: action-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: { }

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v4

      # (optional cache)
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ matrix.python-version }}

      - name: Run local action (declared)
        uses: ./
        with:
          mode: declared
          ignore: pip,setuptools,wheel,ruff
          fail-if-outdated: "false"     # не валим свой CI
          max-unused: "999"
          format: md
          artifact-name: animadao-report-${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}

      - name: Run local action (installed)
        uses: ./
        with:
          mode: installed
          fail-if-outdated: "false"
          artifact-name: animadao-report-installed-${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
